CREATE TABLE IF NOT EXISTS network.ips (
  ip INET NOT NULL,
  create_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ip)
);

CREATE INDEX IF NOT EXISTS ips_ip_idx ON network.ips (ip);
