CREATE TABLE IF NOT EXISTS network.cdns (
  cdn TEXT NOT NULL,
  create_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (cdn)
);

ALTER TABLE network.ips
  ADD COLUMN IF NOT EXISTS is_cdn BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS cdn_fk TEXT REFERENCES network.cdns (cdn);

CREATE INDEX IF NOT EXISTS cdns_cdn_idx ON network.cdns (cdn);
CREATE INDEX IF NOT EXISTS ips_cdn_fk_idx ON network.ips (cdn_fk);
